#!/bin/bash

args=$1
args2=$2

case $args in
  clear-save)
    rm save/*
    ;;

  fill-save)
      python scripts.py fill-save
    ;;

  run-tests)
    pytest managers
    pytest Entity
    ;;

  create-enemy)
    python scripts.py create-enemy "$args2"
    ;;

  refresh-enemy-data)
    ls JSON/Enemies/ | while read -r FILE
      do python scripts.py create-enemy "${FILE%.*}"
    done
  ;;

  create-move)
    python scripts.py create-move "$args2"

esac


