#!/bin/bash

args=$1
args2=$2
args3=$3

case $args in
  clear-save)
    rm save/*
    ;;

  fill-save)
      python scripts.py fill-save
    ;;

  run-tests)
    pytest managers
    pytest Entity
    ;;

  create-enemy)
    python scripts.py create-enemy "$args2"
    ;;

  refresh-enemy-data)
    ls JSON/Enemies/ | while read -r FILE
      do python scripts.py create-enemy "${FILE%.*}"
    done
  ;;

  create-move)
    python scripts.py create-move "$args2"
  ;;

  create-item)
    python scripts.py create-item "$args2"
  ;;

  create-effects)
    python scripts.py create-effects
  ;;

  create-equipment)
    python scripts.py create-equipment
  ;;

  create-fusions)
    python scripts.py create-fusions
  ;;

  validate-fusions)
    python scripts.py validate-fusions
  ;;

  update-saves)
    python scripts.py update-saves
  ;;

  add-status)
    python scripts.py add-status "$args2"
  ;;

  add-event)
    python scripts.py add-event "$args2"
  ;;

  add-quest)
    python scripts.py add-quest "$args2"
  ;;

  add-NPC)
    python scripts.py add-NPC "$args2"
    mkdir NPC_Sprites/"$args2"
  ;;

  add-animation-NPC)
    num=1
    for i in NPC_SPRITES/"$args2"/tile*.png
      do mv "$i" NPC_SPRITES/"$args2"/"$args2"_"$args3"_"$num".png
      num=$((num + 1))
    done
  ;;

  add-animation-Entity)
    num=1
    for i in Entity_Sprites/"$args2"/tile*.png
      do mv "$i" NPC_SPRITES/"$args2"/"$args2"_"$args3"_"$num".png
      num=$((num + 1))
    done


esac


